arr1=`tacggcgcgcagcaaaggtcttgcggacggcgct
gcccgggctggtctcttcgttcaagctcttgctcctcaaaaaatccttcga
ctcggcgctcacactctaattcatgtgcccgaagtccctggccggggtgctcc
ttgcggtccgtgcgaaggtcttgcggacggcgctgccggcgagcctttagcgaaaa
caccggtgtccttggttagacagagaggtcaaaaaaggccggtcgaccgtccctcttgtc
gctgtttgtggatcggctctcatacagctgaatctttctcttcgtccgttccatataaacttc
cgagggtactaagacttacctcagaaaggtcttgcggacggcgctgccctagaggtttctgaccta
ccatacccgacagacctcaaactactcctcgctcgggtcgtcctcctacgtaatcgtgttgtccggaaa
cttctccgagcctcttcctgtgcgcttaaacttctatctctgtccagagtagccctcctttacctccgttct
tctgttgttctgggatcaggaccaaggttaaatccaccaccactactggagtttgaagcaatt`



cut_part='ctcttcgttcaagctcttgctcc'
noVirus=arr1.replace(cut_part, '')
console.log(noVirus.length)